name: test

on:
  push:

jobs:
  go-test:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out
      uses: actions/checkout@v3
    -
      name: Go backup
      run: |
        go build
